files:
  - source: /client/src/translations/en-GB.json
    translation: /client/src/translations/%locale%.json
pull_request_title: "l10n: new translations from Crowdin"
commit_message: "l10n: new translations {languageName}"
