version: '3.8'
services:
  silverdict:
    build: .
    volumes:
      - ./dictionaries/:/home/silverdict/.silverdict/
      # - /path/to/cache/:/home/silverdict/.cache/SilverDict/ # Optional mounting of cache
    restart: unless-stopped
    ports:
      - 2628:2628
